version: '3.7'
networks:
  default:
    external:
      name: network
services:
 postgres:
  restart: always
  container_name: iggnpk_postgres
  build:
   context: .
   dockerfile: dockerfiles/docker_postgres.conf
  ports:
  - "5432:5432"
  volumes:
      - ./dbdata:/var/lib/postgresql/data
 pgbackups:
  image: prodrigestivill/postgres-backup-local
  restart: always
  user: postgres:postgres
  volumes:
   - ./backup:/backups
  links:
   - postgres
  depends_on:
   - postgres
  environment:
   - POSTGRES_HOST=postgres
   - POSTGRES_DB=iggnpk
   - POSTGRES_USER=postgres
   - POSTGRES_PASSWORD=123
   #  - POSTGRES_PASSWORD_FILE=/run/secrets/db_password <-- alternative for POSTGRES_PASSWORD (to use with docker secrets)
   - POSTGRES_EXTRA_OPTS=-Z6 --schema=public --blobs
   - SCHEDULE=@daily
   - BACKUP_KEEP_DAYS=7
   - BACKUP_KEEP_WEEKS=4
   - BACKUP_KEEP_MONTHS=6
   - HEALTHCHECK_PORT=8080
 redis:
  container_name: iggnpk_redis
  image: "redis:alpine"
 django:
  restart: always
  container_name: iggnpk_django
  volumes:
   - ./app:/iggnpk
   - sock:/tmp
  build:
   context: .
   dockerfile: dockerfiles/docker_django.conf
  depends_on:
   - postgres
   - redis
  command: uwsgi --ini /etc/uwsgi.ini
  #command: bash -c "python /iggnpk/manage.py collectstatic --noinput && python /iggnpk/manage.py migrate && python /iggnpk/manage.py runserver 0.0.0.0:8000"
  ports:
   - "8000:8000"
 celery:
  build:
   context: .
   dockerfile: dockerfiles/docker_django.conf
  container_name: iggnpk_celery
  command: celery -A iggnpk worker -l info
  volumes:
   - ./app:/iggnpk
  depends_on:
   - postgres
   - redis
   - django
 celery-beat:
  build:
   context: .
   dockerfile: dockerfiles/docker_django.conf
  container_name: iggnpk_celery_beat
  command: celery -A iggnpk beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
  volumes:
   - ./app:/iggnpk
  depends_on:
   - postgres
   - redis
   - celery
 flower:
  container_name: iggnpk_flower
  image: mher/flower
  environment:
   - CELERY_BROKER_URL=redis://redis:6379/0
   - FLOWER_PORT=8888
  depends_on:
   - celery
   - celery-beat
  ports:
   - 8888:8888
 nginx:
  restart: always
  container_name: iggnpk_nginx
  volumes:
   - ./app:/iggnpk
   - sock:/sock
   - ./letsencrypt:/etc/letsencrypt
   - ./config/nginx/django.conf:/etc/nginx/conf.d/default.conf
  build:
   context: .
   dockerfile: dockerfiles/docker_nginx.conf
  depends_on:
   - django
  ports:
    - "80:80"
    - "443:443"
  environment:
      - VIRTUAL_HOST=iggnpk.ru
      - LETSENCRYPT_HOST=iggnpk.ru
      - LETSENCRYPT_EMAIL=i7ionov@gmail.com

 mail:
  restart: always
  container_name: iggnpk_mail
  image: bytemark/smtp
  ports:
    - "25:25"
  environment:
  - MAILNAME=iggnpk.ru
volumes:
  sock: